# Generated by Django 5.0.7 on 2026-09-23 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ['-created_at']},
        ),
    ]
