# Generated by Django 5.0.7 on 2026-09-23 07:02

import apps.content.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_newslettersubscriber_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageasset',
            name='image',
            field=models.ImageField(upload_to='ngo/images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.content.models.validate_upload_size]),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='ngo/branding/', validators=[apps.content.models.validate_upload_size]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='ngo/partners/', validators=[apps.content.models.validate_upload_size]),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(upload_to='ngo/reports/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), apps.content.models.validate_upload_size]),
        ),
    ]
