# Generated by Django 5.0.7 on 2026-09-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_imageasset_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='purpose',
            field=models.CharField(default='General support', max_length=160),
        ),
    ]
