export const ROUTES = {
  home: "/",
  about: "/about",
  programs: "/programs",
  projects: "/projects",
  impact: "/impact",
  events: "/events",
  news: "/news",
  gallery: "/gallery",
  donate: "/donate",
  volunteer: "/volunteer",
  partnership: "/partnership",
  team: "/team",
  reports: "/reports",
  contact: "/contact",
  faq: "/faq",
  privacy: "/privacy-policy",
  terms: "/terms",
  cancellation: "/cancellation-policy",
  notFound: "/404",
  programDetail: (slug: string) => `/programs/${slug}`,
  projectDetail: (slug: string) => `/projects/${slug}`,
  eventDetail: (slug: string) => `/events/${slug}`,
  newsDetail: (slug: string) => `/news/${slug}`,
} as const;
