import {
  Baby,
  ChartColumn,
  Ear,
  Eye,
  Flower2,
  FolderKanban,
  GraduationCap,
  HandHeart,
  Handshake,
  HeartHandshake,
  HeartPulse,
  Layers,
  Leaf,
  Lightbulb,
  MapPin,
  PencilRuler,
  Route,
  ShieldCheck,
  Sprout,
  Users,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/types";

/** Data files reference icons by name so they stay serialisable (API-ready). */
export const iconMap: Record<IconName, LucideIcon> = {
  graduation: GraduationCap,
  health: HeartPulse,
  women: Flower2,
  children: Baby,
  community: Users,
  environment: Leaf,
  lives: HeartHandshake,
  communities: MapPin,
  projects: FolderKanban,
  volunteers: HandHeart,
  programs: Layers,
  partners: Handshake,
  integrity: ShieldCheck,
  inclusion: Users,
  transparency: Eye,
  compassion: HandHeart,
  innovation: Lightbulb,
  sustainability: Sprout,
  listen: Ear,
  codesign: PencilRuler,
  deliver: Route,
  measure: ChartColumn,
};
